package com.example.sample.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.sample.dao.UserInf;

import com.example.sample.dao.UserInfDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userInfDaoConfig;

    private final UserInfDao userInfDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userInfDaoConfig = daoConfigMap.get(UserInfDao.class).clone();
        userInfDaoConfig.initIdentityScope(type);

        userInfDao = new UserInfDao(userInfDaoConfig, this);

        registerDao(UserInf.class, userInfDao);
    }
    
    public void clear() {
        userInfDaoConfig.clearIdentityScope();
    }

    public UserInfDao getUserInfDao() {
        return userInfDao;
    }

}
